services:
  backend:
    container_name: sm-backend-dev
    image: sm-backend:dev
    build:
      context: .
      dockerfile: devops/Dockerfile
    command: "/bin/sh -c 'npm install && npm run migration:run && npm run start:dev'"
    working_dir: /app
    volumes:
      - "./:/app"
    ports:
      - "4000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    restart: always